### ISSUE TITLE
Reusable DataAccessModule

### ISSUE THREAD

**Issue by ghost** [Institute-Web-Science-and-Technologies/koldfish-dam#1]
Currently, the DataAccessModule can handle only one DataAccessModuleListener. Thus, each DataAccessModule can only be used for one dereference request or you would have to implement a DataAccessModuleListener that implements the listener pattern again.

A better design decision would be to add the following methods to the DataAccessModule:
`addListener(DataAccessModuleListener listener)`
`removeListener(DataAccessModuleListener listener)`

The questions remains, how can you identify, which DerefResponse or ErrorResponse belongs to which deref request. There fore the response classes might provide a method:
`isResponseForDeref(long encodedIRI)`

**Comment by lkastler** [comment]
[Done](https://github.com/Institute-Web-Science-and-Technologies/koldfish-dam/tree/21d692e8edef30d802f717db8b807e573acb9230).

I changed single object listener to list.

For the second part: you can identify which response message belongs to which request by comparing the encoded IRIs of them.
