### ISSUE TITLE
Random deref response should contain dereffed IRI in responded triples

### ISSUE THREAD

**Issue by ghost** [Institute-Web-Science-and-Technologies/koldfish-dam#2]
The DummyDataAccessModule produces random descriptions of an IRI. Currently these describing triples consist of three random long values. The subject or the object of these triples should contain the requested (encoded) IRI so that they are describing triples indeed.

**Comment by lkastler** [comment]
Is this really a necessary requirement?
I agree that responded triples should contain the encoded IRI for real, but I don't think that the DummyDataAccessModule should produce realistic data. It is for testing purposes. If it would be realistic, a triple `ex:A ex:P ex:B` should be returned for dereferencing `ex:A` and `ex:B` (depending on the definition of what dereferencing does).

**Comment by lkastler** [comment]
done, just for convenience
