### ISSUE TITLE
Throw more precise Exceptions

### ISSUE THREAD

**Issue by ghost** [Institute-Web-Science-and-Technologies/koldfish-dam#5]
The constructor of JmsDataAccessModule declares throws Exception. The constructor should throw the precise Exceptions instead.

**Comment by lkastler** [comment]
Each message contains a precise description with `getMessage()`. Throwing different Exception implementations leads to complications since each Exception class must be available on both sides for serialization.

**Comment by ghost** [comment]
I assume you do not have something like `throw new Exception("...")` in your code, do you?
