### ISSUE TITLE
DerefResponse - Constructor - Listener instead of list

### ISSUE THREAD

**Issue by ghost** [Institute-Web-Science-and-Technologies/koldfish-dam#6]
The Class "DerefResponseImpl" should only take an Iterator<long[]> instead of a List<long[]> as it only provides access to an Iterator and not to the list itself.
This is mostly also required for testing / benchmarking the data service backend. The tests / benchmarks are using a huge data and as a result can not provide a list but only an Iterator<long[]> who will iterate a file.

@lkastler

**Comment by lkastler** [comment]
done in https://github.com/Institute-Web-Science-and-Technologies/koldfish-dam/commit/01c3e1a8ccce29cb6339c8c8c90b3b2cbede4ac2

**Comment by ghost** [comment]
Hey Leon,
did you pushed this to maven?

**Comment by lkastler** [comment]
yes
